### ISSUE TITLE
5.0.0 release is missing json schema files

### ISSUE THREAD

**Issue by mtreinish** [jupyter/nbformat#155]
The recent 5.0.0 release just broke CI on qiskit-terra:

https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=6785&view=logs&j=b59abcfc-1a00-5817-c1e4-d93e425db181&t=5e8156b8-6f6a-5ddc-c9a9-7a100c55c902&l=2304

```
File "/home/vsts/work/1/s/test/python/tools/jupyter/test_notebooks.py", line 64, in test_jupyter_jobs_pbars
  'notebooks/test_pbar_status.ipynb'))
File "/home/vsts/work/1/s/test/python/tools/jupyter/test_notebooks.py", line 44, in _execute_notebook
  notebook = nbformat.read(file_, as_version=4)
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/__init__.py", line 140, in read
  return reads(fp.read(), as_version, **kwargs)
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/__init__.py", line 77, in reads
  validate(nb)
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/validator.py", line 276, in validate
  relax_add_props=relax_add_props):
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/validator.py", line 298, in iter_validate
  validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/validator.py", line 69, in get_validator
  schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
File "/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/validator.py", line 106, in _get_schema_json
  with open(schema_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/nbformat/v4/nbformat.v4.2.schema.json'
```

It looks like the jsonschema file `nbformat.v4.2.schema.json` was not included in the sdist or the wheel published to pypi. So the installed package via pip will always raise this error.

**Comment by MSeal** [comment]
That is odd, is it also happening for the 5.0.1 release -- I just ran a minor fix?

Apologies if there where issues -- I had to generate actual release docs as there were some unwritten assumption in releasing the package we had to rediscover the hard way.

**Comment by MSeal** [comment]
Ok looks like that's also missing -- I'll get a patch release going to add the missing files into the package :/

**Comment by vEpiphyte** [comment]
@MSeal This is what I see when I busted open the 5.0.1 patch release.

```
$ tar --list --verbose --file nbformat-5.0.1.tar  | grep json
-rw-rw-r-- mseal/mseal     610 2020-01-06 22:28 nbformat-5.0.1/package.json
-rw-rw-r-- mseal/mseal    1471 2020-01-06 21:02 nbformat-5.0.1/nbformat/v1/nbjson.py
-rw-rw-r-- mseal/mseal     219 2019-12-30 05:58 nbformat-5.0.1/nbformat/v1/tests/test_json.py
-rw-rw-r-- mseal/mseal    1843 2020-01-06 21:02 nbformat-5.0.1/nbformat/v4/nbjson.py
-rw-rw-r-- mseal/mseal   19544 2020-01-06 22:26 nbformat-5.0.1/nbformat/v4/nbformat.v4.schema.json
-rw-rw-r-- mseal/mseal    4942 2020-01-06 22:26 nbformat-5.0.1/nbformat/v4/tests/test_json.py
-rw-rw-r-- mseal/mseal    1451 2020-01-06 21:02 nbformat-5.0.1/nbformat/v3/nbjson.py
-rw-rw-r-- mseal/mseal   14910 2019-12-30 05:58 nbformat-5.0.1/nbformat/v3/nbformat.v3.schema.json
-rw-rw-r-- mseal/mseal    3377 2020-01-06 21:02 nbformat-5.0.1/nbformat/v3/tests/test_json.py
-rw-rw-r-- mseal/mseal    1936 2019-12-30 05:58 nbformat-5.0.1/nbformat/v2/nbjson.py
-rw-rw-r-- mseal/mseal     926 2019-12-30 05:58 nbformat-5.0.1/nbformat/v2/tests/test_json.py
$ unzip -l nbformat-5.0.1-py3-none-any.whl | grep json
     1471  2020-01-06 21:02   nbformat/v1/nbjson.py
      219  2019-12-30 05:58   nbformat/v1/tests/test_json.py
     1936  2019-12-30 05:58   nbformat/v2/nbjson.py
      926  2019-12-30 05:58   nbformat/v2/tests/test_json.py
    14910  2019-12-30 05:58   nbformat/v3/nbformat.v3.schema.json
     1451  2020-01-06 21:02   nbformat/v3/nbjson.py
     3377  2020-01-06 21:02   nbformat/v3/tests/test_json.py
    19544  2020-01-06 22:26   nbformat/v4/nbformat.v4.schema.json
     1843  2020-01-06 21:02   nbformat/v4/nbjson.py
     4942  2020-01-06 22:26   nbformat/v4/tests/test_json.py
```

**Comment by willcrichton** [comment]
After installing 5.0.1, I get the following error trying to create a new notebook:

```
[I 15:03:59.956 NotebookApp] Creating new notebook in
[E 15:03:59.957 NotebookApp] Uncaught exception POST /api/contents (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/contents', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 202, in post
        yield self._new_untitled(path, type=type, ext=ext)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 154, in _new_untitled
        model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
        return self.new(model, path)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 416, in new
        model['content'] = new_notebook()
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 159, in new_notebook
        validate(nb)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/v4/nbbase.py", line 37, in validate
        return validate(node, ref=ref, version=nbformat)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/validator.py", line 276, in validate
        relax_add_props=relax_add_props):
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/validator.py", line 298, in iter_validate
        validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/validator.py", line 69, in get_validator
        schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
      File "/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/validator.py", line 106, in _get_schema_json
        with open(schema_path) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/will/Code/inliner/.env/lib/python3.7/site-packages/nbformat/v4/nbformat.v4.3.schema.json'
```

**Comment by MSeal** [comment]
Hmm I looked at 4.4.0 release and it similarly did not have `nbformat.v4.2.schema.json`. I believe it's because of the version difference, those files should have been there but it was falling back to `4.schema.json`. I'm working on validating the fix and will release imminently.

**Comment by MSeal** [comment]
5.0.2 just released with a fix for the issue referenced. I didn't check all examples posted but two of the failure patterns referenced were fixed with the new release locally on my machine.

**Comment by MSeal** [comment]
A debug statement was left in -- 5.0.3 removed it but is functionally identical to 5.0.2. Apologies for the inconvenience this caused.

**Comment by rgbkrk** [comment]
Thank you @MSeal

**Comment by MSeal** [comment]
Closing as multiple folks are reporting this issue as fixed with >= 5.0.2

**Comment by dkleissa** [comment]
We run an nbconvert service that was failing CI. Rolling back the temporary change to pin nbformat version to 4.4.0 now installs 5.0.2. Confirming that CI passes and things seem to work. Thanks for the quick response!

**Comment by IveJ** [comment]
Thanks.
