### ISSUE TITLE
When using fastjsonschema, nbformat.v4.new_code_cell throws error

### ISSUE THREAD

**Issue by metalhead95** [jupyter/nbformat#197]
Reproducer - 
 `env NBFORMAT_VALIDATOR=fastjsonschema python3 -c 'import nbformat; nbformat.v4.new_code_cell()'`

Output- 
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/nbformat/v4/nbbase.py", line 124, in new_code_cell
    validate(cell, 'code_cell')
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/nbformat/v4/nbbase.py", line 38, in validate
    return validate(node, ref=ref, version=nbformat)
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/nbformat/validator.py", line 262, in validate
    relax_add_props=relax_add_props):
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/nbformat/validator.py", line 292, in iter_validate
    errors = validator.iter_errors(nbdict, {'$ref' : '#/definitions/%s' % ref})
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/nbformat/json_compat.py", line 51, in iter_errors
    validate_func = self._validator if schema is None else fastjsonschema.compile(schema)
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/__init__.py", line 167, in compile
    global_state = code_generator.global_state
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/draft04.py", line 70, in global_state
    res = super().global_state
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/generator.py", line 80, in global_state
    self._generate_func_code()
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/generator.py", line 118, in _generate_func_code
    self.generate_func_code()
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/generator.py", line 132, in generate_func_code
    self.generate_validation_function(uri, name)
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/generator.py", line 140, in generate_validation_function
    with self._resolver.resolving(uri) as definition:
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/ref_resolver.py", line 135, in resolving
    yield resolve_path(schema, fragment)
  File "/Users/maharshi/Library/Python/3.7/lib/python/site-packages/fastjsonschema/ref_resolver.py", line 41, in resolve_path
    raise JsonSchemaDefinitionException('Unresolvable ref: {}'.format(part))
fastjsonschema.exceptions.JsonSchemaDefinitionException: Unresolvable ref: definitions```

**Comment by goanpeca** [comment]
Thanks!, I will take a look at it!
