### ISSUE TITLE
ImportError with encodestring from package base64

### ISSUE THREAD

**Issue by Alonoparag** [jupyter/nbformat#215]
**Describe the bug**
Jupyter experiences a fatal error on startup. ImportError: cannot import name 'encodestring' from 'base64' (/usr/lib/python3.9/base64.py). 'encodestring is a removed function in python 3.9.
Apparently this error is caused by nbformat importing base64

**To Reproduce**
1. Python version 3.9
2. Run any Jupyter product (Notebook, lab).

**Expected behavior**
Traceback (most recent call last):
File "/home/user/.local/bin/jupyter-notebook", line 5, in
from notebook.notebookapp import main
File "/home/user/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 83, in
from .services.contents.manager import ContentsManager
File "/home/user/.local/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 17, in
from nbformat import sign, validate as validate_nb, ValidationError
File "/home/user/.local/lib/python3.9/site-packages/nbformat/init.py", line 14, in
from . import v1
File "/home/user/.local/lib/python3.9/site-packages/nbformat/v1/init.py", line 19, in
from .nbjson import reads as reads_json, writes as writes_json
File "/home/user/.local/lib/python3.9/site-packages/nbformat/v1/nbjson.py", line 19, in
from base64 import encodestring
ImportError: cannot import name 'encodestring' from 'base64' (/usr/lib/python3.9/base64.py)

**Desktop (please complete the following information):**

*    OS: Manjaro 20.12.2 Gnome 3.38.4
*    Browser Firefox 86.0.01-01
*    Jupyter 4.4.0

**Comment by goanpeca** [comment]
@Alonoparag what version of nbformat are you using?

**Comment by kylepolich** [comment]
I'm having this problem also.  Any solution?

**Comment by vidartf** [comment]
As an informational point, `encodestring` has not been in use in `nbformat.v1.json` since version 5.0.0. If you are seeing this error, it is likely you are still on version 4.x of nbconvert. If there is something preventing you from updating to the 5.x strain while on a recent version of Python, please comment why. Maybe if the case seems important enough, you can convince someone that a backported fix to 4.x is needed.

@ralphbird It seems likely that you are not actually getting version 5.1.3. Please inspect the code in your env to verify the version string in your installed package.
